// VBA → TypeScript Code Generator
// Walks the AST and emits TypeScript source

import type {
  VBAType, ModuleNode, FunctionNode, DeclarationNode, StatementNode, ExpressionNode,
  DimDeclarationNode, ConstDeclarationNode, AssignmentNode, CallStatementNode,
  IfStatementNode, ForStatementNode, ForEachStatementNode, WhileStatementNode,
  DoStatementNode, SelectStatementNode, ExitStatementNode, WithStatementNode,
  OnErrorStatementNode, ReturnStatementNode,
  BinaryExpressionNode, UnaryExpressionNode, CallExpressionNode,
  MemberExpressionNode, IndexExpressionNode, LiteralNode, IdentifierNode,
  ParameterNode,
} from './ast';

// VBA built-in → TypeScript/runtime function mapping
const BUILTIN_MAP: Record<string, string> = {
  // String functions
  Left: 'vba.Left', Right: 'vba.Right', Mid: 'vba.Mid', Len: 'vba.Len',
  Trim: 'vba.Trim', LTrim: 'vba.LTrim', RTrim: 'vba.RTrim',
  InStr: 'vba.InStr', InStrRev: 'vba.InStrRev', Replace: 'vba.Replace',
  UCase: 'vba.UCase', LCase: 'vba.LCase', Space: 'vba.Space',
  StrReverse: 'vba.StrReverse', String: 'vba.StringFn', Format: 'vba.Format',
  // Math
  Abs: 'Math.abs', Round: 'vba.Round', Int: 'Math.trunc',
  Sqr: 'Math.sqrt', Exp: 'Math.exp', Log: 'Math.log',
  Sin: 'Math.sin', Cos: 'Math.cos', Tan: 'Math.tan', Atn: 'Math.atan',
  // Type conversion
  CInt: 'vba.CInt', CLng: 'vba.CLng', CDbl: 'vba.CDbl', CStr: 'vba.CStr',
  CBool: 'vba.CBool', CDate: 'vba.CDate', CCur: 'vba.CCur',
  // Type checking
  IsNull: 'vba.IsNull', IsEmpty: 'vba.IsEmpty', IsNumeric: 'vba.IsNumeric',
  IsDate: 'vba.IsDate', IsError: 'vba.IsError', IsArray: 'vba.IsArray',
  IsObject: 'vba.IsObject', TypeName: 'vba.TypeName', VarType: 'vba.VarType',
  // Date
  Now: 'vba.Now', Date: 'vba.DateFn', Time: 'vba.TimeFn',
  DateAdd: 'vba.DateAdd', DateDiff: 'vba.DateDiff', DatePart: 'vba.DatePart',
  Month: 'vba.Month', Year: 'vba.Year', Day: 'vba.Day',
  Hour: 'vba.Hour', Minute: 'vba.Minute', Second: 'vba.Second',
  Weekday: 'vba.Weekday', DateSerial: 'vba.DateSerial', TimeSerial: 'vba.TimeSerial',
  // Array
  UBound: 'vba.UBound', LBound: 'vba.LBound', Split: 'vba.Split', Join: 'vba.Join',
  // Excel functions
  Sum: 'excel.SUM', Average: 'excel.AVERAGE', Count: 'excel.COUNT',
  Max: 'excel.MAX', Min: 'excel.MIN', Vlookup: 'excel.VLOOKUP',
  Hlookup: 'excel.HLOOKUP', Index: 'excel.INDEX', Match: 'excel.MATCH',
  If: 'excel.IF', SumIf: 'excel.SUMIF', CountIf: 'excel.COUNTIF',
  // IO (stubbed)
  MsgBox: 'vba.MsgBox', InputBox: 'vba.InputBox', Print: 'console.log',
  Debug: 'console',
};

const OPERATOR_MAP: Record<string, string> = {
  '=': '===', '<>': '!==', '\\': 'Math.trunc',
  '&': '+', 'And': '&&', 'Or': '||', 'Not': '!', 'Xor': '^',
  'Mod': '%', '^': '**', 'Is': '===', 'Like': 'vba.Like',
};

function vbaTypeToTS(t?: VBAType): string {
  if (!t) return 'any';
  if (typeof t === 'string') {
    const map: Record<string, string> = {
      Integer: 'number', Long: 'number', Single: 'number', Double: 'number',
      Currency: 'number', Byte: 'number', LongLong: 'number', Decimal: 'number',
      String: 'string', Boolean: 'boolean', Date: 'Date',
      Variant: 'any', Object: 'object', Empty: 'undefined', Null: 'null', Error: 'Error',
    };
    return map[t] ?? 'any';
  }
  if (t.kind === 'Array') return `${vbaTypeToTS(t.elementType)}[]`;
  if (t.kind === 'UserDefined') return t.name;
  return 'any';
}

export class Transpiler {
  private indent = 0;
  private lines: string[] = [];
  private functionName = ''; // for implicit return assignment (VBA assigns to function name)

  transpileModule(module: ModuleNode): string {
    this.lines = [];
    this.indent = 0;

    this.emit('// Auto-generated by VBA Transpiler — do not edit manually');
    this.emit("import * as vba from './runtime/vba';");
    this.emit("import * as excel from './runtime/excel';");
    this.emit('');

    for (const decl of module.declarations) {
      this.transpileDeclaration(decl);
    }

    return this.lines.join('\n');
  }

  private emit(line: string) {
    const prefix = '  '.repeat(this.indent);
    this.lines.push(line === '' ? '' : prefix + line);
  }

  private block(fn: () => void) {
    this.indent++;
    fn();
    this.indent--;
  }

  private transpileDeclaration(decl: DeclarationNode) {
    if (decl.kind === 'Function' || decl.kind === 'Sub' || decl.kind === 'Property') {
      this.transpileFunction(decl);
    } else if (decl.kind === 'DimDeclaration') {
      this.transpileDim(decl);
    } else if (decl.kind === 'ConstDeclaration') {
      this.transpileConst(decl);
    }
  }

  private transpileFunction(fn: FunctionNode) {
    const vis = fn.isPublic ? 'export ' : '';
    const params = fn.params.map(p => this.transpileParam(p)).join(', ');
    const ret = fn.kind !== 'Sub' ? `: ${vbaTypeToTS(fn.returnType)}` : ': void';
    this.functionName = fn.name;

    // Implicit return variable: VBA assigns to function name to return
    let returnVarDecl = '';
    if (fn.kind === 'Function' && fn.returnType) {
      const defaultVal = this.defaultValue(fn.returnType);
      returnVarDecl = `let ${fn.name}: ${vbaTypeToTS(fn.returnType)} = ${defaultVal};`;
    }

    this.emit(`${vis}function ${fn.name}(${params})${ret} {`);
    this.block(() => {
      if (returnVarDecl) this.emit(returnVarDecl);
      for (const stmt of fn.body) {
        this.transpileStatement(stmt);
      }
      if (fn.kind === 'Function' && fn.returnType) {
        this.emit(`return ${fn.name};`);
      }
    });
    this.emit('}');
    this.emit('');
    this.functionName = '';
  }

  private defaultValue(type: VBAType): string {
    if (typeof type === 'string') {
      if (['Integer', 'Long', 'Single', 'Double', 'Currency', 'Byte', 'LongLong'].includes(type)) return '0';
      if (type === 'String') return '""';
      if (type === 'Boolean') return 'false';
      if (type === 'Date') return 'new Date()';
    }
    return 'undefined as any';
  }

  private transpileParam(p: ParameterNode): string {
    const name = p.name;
    const type = vbaTypeToTS(p.type);
    if (p.paramArray) return `...${name}: ${type}[]`;
    if (p.optional && p.defaultValue) return `${name}: ${type} = ${this.transpileExpr(p.defaultValue)}`;
    if (p.optional) return `${name}?: ${type}`;
    return `${name}: ${type}`;
  }

  private transpileStatement(stmt: StatementNode) {
    switch (stmt.kind) {
      case 'DimDeclaration': return this.transpileDim(stmt);
      case 'ConstDeclaration': return this.transpileConst(stmt);
      case 'Assignment': return this.transpileAssignment(stmt);
      case 'CallStatement': return this.emit(this.transpileExpr(stmt.expression as any) + ';');
      case 'IfStatement': return this.transpileIf(stmt);
      case 'ForStatement': return this.transpileFor(stmt);
      case 'ForEachStatement': return this.transpileForEach(stmt);
      case 'WhileStatement': return this.transpileWhile(stmt);
      case 'DoStatement': return this.transpileDo(stmt);
      case 'SelectStatement': return this.transpileSelect(stmt);
      case 'ExitStatement': return this.transpileExit(stmt);
      case 'WithStatement': return this.transpileWith(stmt);
      case 'OnErrorStatement': return this.transpileOnError(stmt);
      case 'ReturnStatement': return this.transpileReturn(stmt);
    }
  }

  private transpileDim(d: DimDeclarationNode) {
    const type = vbaTypeToTS(d.type);
    const init = d.initializer ? ` = ${this.transpileExpr(d.initializer)}` : (type !== 'any' ? ` = ${this.defaultValue(d.type!)}` : '');
    this.emit(`let ${d.name}: ${type}${init};`);
  }

  private transpileConst(c: ConstDeclarationNode) {
    const type = vbaTypeToTS(c.type);
    this.emit(`const ${c.name}: ${type} = ${this.transpileExpr(c.value)};`);
  }

  private transpileAssignment(a: AssignmentNode) {
    const target = this.transpileExpr(a.target);
    const value = this.transpileExpr(a.value);
    // VBA function implicit return: assigning to function name sets return value
    if (a.target.kind === 'Identifier' && (a.target as IdentifierNode).name === this.functionName) {
      this.emit(`${target} = ${value};`);
    } else {
      this.emit(`${target} = ${value};`);
    }
  }

  private transpileIf(stmt: IfStatementNode) {
    this.emit(`if (${this.transpileExpr(stmt.condition)}) {`);
    this.block(() => { for (const s of stmt.thenBranch) this.transpileStatement(s); });
    for (const elif of stmt.elseIfClauses) {
      this.emit(`} else if (${this.transpileExpr(elif.condition)}) {`);
      this.block(() => { for (const s of elif.body) this.transpileStatement(s); });
    }
    if (stmt.elseBranch) {
      this.emit('} else {');
      this.block(() => { for (const s of stmt.elseBranch!) this.transpileStatement(s); });
    }
    this.emit('}');
  }

  private transpileFor(stmt: ForStatementNode) {
    const from = this.transpileExpr(stmt.from);
    const to = this.transpileExpr(stmt.to);
    const step = stmt.step ? this.transpileExpr(stmt.step) : '1';
    const v = stmt.variable;
    const op = stmt.step ? `/* step=${step} */` : '';
    this.emit(`for (let ${v}: number = ${from}; ${v} <= ${to}; ${v} += ${step}) { ${op}`);
    this.block(() => { for (const s of stmt.body) this.transpileStatement(s); });
    this.emit('}');
  }

  private transpileForEach(stmt: ForEachStatementNode) {
    const col = this.transpileExpr(stmt.collection);
    this.emit(`for (const ${stmt.variable} of ${col}) {`);
    this.block(() => { for (const s of stmt.body) this.transpileStatement(s); });
    this.emit('}');
  }

  private transpileWhile(stmt: WhileStatementNode) {
    this.emit(`while (${this.transpileExpr(stmt.condition)}) {`);
    this.block(() => { for (const s of stmt.body) this.transpileStatement(s); });
    this.emit('}');
  }

  private transpileDo(stmt: DoStatementNode) {
    if (!stmt.condition || (!stmt.conditionAtEnd && stmt.whileOrUntil === 'While')) {
      const cond = stmt.condition ? this.transpileExpr(stmt.condition) : 'true';
      const negated = stmt.whileOrUntil === 'Until' ? `!(${cond})` : cond;
      this.emit(`while (${negated}) {`);
      this.block(() => { for (const s of stmt.body) this.transpileStatement(s); });
      this.emit('}');
    } else {
      this.emit('do {');
      this.block(() => { for (const s of stmt.body) this.transpileStatement(s); });
      const cond = stmt.condition ? this.transpileExpr(stmt.condition) : 'false';
      const negated = stmt.whileOrUntil === 'Until' ? `!(${cond})` : cond;
      this.emit(`} while (${negated});`);
    }
  }

  private transpileSelect(stmt: SelectStatementNode) {
    const expr = this.transpileExpr(stmt.expression);
    this.emit(`switch (${expr}) {`);
    this.block(() => {
      for (const c of stmt.cases) {
        if (c.values === 'Else') {
          this.emit('default:');
        } else {
          for (const v of c.values) {
            this.emit(`case ${this.transpileExpr(v)}:`);
          }
        }
        this.block(() => {
          for (const s of c.body) this.transpileStatement(s);
          this.emit('break;');
        });
      }
    });
    this.emit('}');
  }

  private transpileExit(stmt: ExitStatementNode) {
    if (stmt.target === 'Function' || stmt.target === 'Sub' || stmt.target === 'Property') {
      if (this.functionName) {
        this.emit(`return ${this.functionName};`);
      } else {
        this.emit('return;');
      }
    } else {
      this.emit('break;');
    }
  }

  private transpileWith(stmt: WithStatementNode) {
    // Inline With as IIFE with a reference variable
    const obj = this.transpileExpr(stmt.object);
    this.emit(`{`);
    this.block(() => {
      this.emit(`const _with = ${obj};`);
      for (const s of stmt.body) this.transpileStatement(s);
    });
    this.emit('}');
  }

  private transpileOnError(stmt: OnErrorStatementNode) {
    if (stmt.kind2 === 'Resume') {
      this.emit('// On Error Resume Next — errors suppressed (not directly portable; use try/catch)');
    } else if (stmt.kind2 === 'GoTo0') {
      this.emit('// On Error GoTo 0 — default error handling restored');
    } else {
      this.emit(`// On Error GoTo ${stmt.label} — label-based error handling not directly portable`);
    }
  }

  private transpileReturn(stmt: ReturnStatementNode) {
    if (stmt.value) this.emit(`return ${this.transpileExpr(stmt.value)};`);
    else this.emit('return;');
  }

  private transpileExpr(expr: ExpressionNode): string {
    switch (expr.kind) {
      case 'Literal': return this.transpileLiteral(expr as LiteralNode);
      case 'Identifier': return this.mapIdentifier((expr as IdentifierNode).name);
      case 'BinaryExpression': return this.transpileBinary(expr as BinaryExpressionNode);
      case 'UnaryExpression': {
        const u = expr as UnaryExpressionNode;
        const op = OPERATOR_MAP[u.operator] ?? u.operator;
        return `${op}(${this.transpileExpr(u.operand)})`;
      }
      case 'CallExpression': return this.transpileCall(expr as CallExpressionNode);
      case 'MemberExpression': return this.transpileMember(expr as MemberExpressionNode);
      case 'IndexExpression': {
        const ix = expr as IndexExpressionNode;
        const obj = this.transpileExpr(ix.object);
        const idxs = ix.indices.map(i => this.transpileExpr(i)).join(', ');
        // VBA arrays are 0 or 1-based — emit helper call
        return `${obj}[${idxs}]`;
      }
      case 'ParenExpression': return `(${this.transpileExpr((expr as any).expression)})`;
      case 'TypeCast': return this.transpileExpr((expr as any).expression);
      default: return `/* unknown expr: ${(expr as any).kind} */`;
    }
  }

  private transpileLiteral(lit: LiteralNode): string {
    if (lit.value === null) return 'null';
    if (lit.rawType === 'Boolean') return String(lit.value);
    if (lit.rawType === 'String') return JSON.stringify(lit.value);
    if (lit.rawType === 'Date') return `new Date("${lit.value}")`;
    return String(lit.value);
  }

  private mapIdentifier(name: string): string {
    // Common VBA globals
    const globals: Record<string, string> = {
      True: 'true', False: 'false', Nothing: 'null', Null: 'null', Empty: 'undefined',
      Me: 'this', ThisWorkbook: 'workbook', ActiveSheet: 'activeSheet',
    };
    return globals[name] ?? name;
  }

  private transpileBinary(expr: BinaryExpressionNode): string {
    const left = this.transpileExpr(expr.left);
    const right = this.transpileExpr(expr.right);
    let op = OPERATOR_MAP[expr.operator] ?? expr.operator;

    if (expr.operator === '\\') {
      return `Math.trunc(${left} / ${right})`;
    }
    if (expr.operator === 'Like') {
      return `vba.Like(${left}, ${right})`;
    }
    if (expr.operator === '&') {
      return `String(${left}) + String(${right})`;
    }
    return `${left} ${op} ${right}`;
  }

  private transpileCall(expr: CallExpressionNode): string {
    const mapped = BUILTIN_MAP[expr.callee] ?? BUILTIN_MAP[expr.callee.toLowerCase()];
    const callee = mapped ?? expr.callee;
    const args = expr.args.map(a => this.transpileExpr(a)).join(', ');
    return `${callee}(${args})`;
  }

  private transpileMember(expr: MemberExpressionNode): string {
    const obj = this.transpileExpr(expr.object);
    if (expr.args) {
      const args = expr.args.map(a => this.transpileExpr(a)).join(', ');
      return `${obj}.${expr.member}(${args})`;
    }
    return `${obj}.${expr.member}`;
  }
}
